[build]
  command = "npm install"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "netlify-plugin-subfont"

  [plugins.inputs]
    entryPoints = ["spa/index.html"]
    recursive   = true
    fontDisplay = "swap"
    inlineCss   = true
    excludeSources = ["**/jsdelivr.net/**tabler*"]
